### ISSUE TITLE
fatal: cannot create directory at 'general/aux': Invalid argument

### ISSUE THREAD

**Issue by feefladder** [gis-ops/tutorials#55]
I cannot clone the directory due to the following, spurious error.
On 
```
git restore --staged .
git add general/aux
git add news/         #this also gave an error?
git commit -m "random message"
git reset --hard
```
this was resolved, but this is of course by far a sub-optimal solution.

**Comment by chrstnbwnkl** [comment]
Thanks for opening an issue! Can you provide more detail on how you're cloning the repo and what error it's giving you?

For me, simply cloning via HTTP is working just fine:
```sh
git clone https://github.com/gis-ops/tutorials.git
```

**Comment by feefladder** [comment]
I clone over SSH, on a Ubuntu (Pop-os) system. Let me see if cloning over https works
