### ISSUE TITLE
Some inquiries about the plugin ：qGis-Valhalla

### ISSUE THREAD

**Issue by luoxinkaikevin** [gis-ops/tutorials#59]
Hello, I am very interested in your qgis plugin, and now I have a new requirement: when routing, can I select a starting point and multiple destination points, and then generate multiple paths;
If the current plug-in version can realize this function, can you guide how to do it? If this function cannot be realized at present, I need to carry out secondary development on the basis of the original plug-in. Can you provide some solutions and source code modification and Guidance?
I look forward to your answer very much. If possible, I hope to establish long-term communication with you and learn morn about this plugin.

**Comment by nilsnolde** [comment]
It's open source: https://github.com/gis-ops/valhalla-qgis-plugin. Be aware of the GPL license though. 

Also, you can ask us on enquiry@gis-ops.com for commercial support.
